CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE clients (
    clientid integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    CONSTRAINT clients_pkey PRIMARY KEY (clientid)
);

CREATE TABLE products (
    productid integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    description character varying(100),
    price numeric(10,2) NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (productid)
);

CREATE TABLE orders (
    orderid integer GENERATED BY DEFAULT AS IDENTITY,
    clientid integer NOT NULL,
    orderdate timestamp without time zone NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (orderid),
    CONSTRAINT orders_clientid_fkey FOREIGN KEY (clientid) REFERENCES clients (clientid)
);

CREATE TABLE orderdetails (
    orderdetailid integer GENERATED BY DEFAULT AS IDENTITY,
    orderid integer NOT NULL,
    productid integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT orderdetails_pkey PRIMARY KEY (orderdetailid),
    CONSTRAINT orderdetails_orderid_fkey FOREIGN KEY (orderid) REFERENCES orders (orderid),
    CONSTRAINT orderdetails_productid_fkey FOREIGN KEY (productid) REFERENCES products (productid)
);

CREATE INDEX "IX_orderdetails_orderid" ON orderdetails (orderid);

CREATE INDEX "IX_orderdetails_productid" ON orderdetails (productid);

CREATE INDEX "IX_orders_clientid" ON orders (clientid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260622193022_InitialCreate', '9.0.17');

COMMIT;

