// <auto-generated />
using System;
using Lab13_HenryVentura.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lab13_HenryVentura.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Clientid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clientid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Clientid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Clientid")
                        .HasName("clients_pkey");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orderid"));

                    b.Property<int>("Clientid")
                        .HasColumnType("integer")
                        .HasColumnName("clientid");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("orderdate");

                    b.HasKey("Orderid")
                        .HasName("orders_pkey");

                    b.HasIndex("Clientid");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Orderdetail", b =>
                {
                    b.Property<int>("Orderdetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderdetailid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orderdetailid"));

                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Orderdetailid")
                        .HasName("orderdetails_pkey");

                    b.HasIndex("Orderid");

                    b.HasIndex("Productid");

                    b.ToTable("orderdetails", (string)null);
                });

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Productid"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Productid")
                        .HasName("products_pkey");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Order", b =>
                {
                    b.HasOne("Lab13_HenryVentura.Domain.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("Clientid")
                        .IsRequired()
                        .HasConstraintName("orders_clientid_fkey");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Orderdetail", b =>
                {
                    b.HasOne("Lab13_HenryVentura.Domain.Entities.Order", "Order")
                        .WithMany("Orderdetails")
                        .HasForeignKey("Orderid")
                        .IsRequired()
                        .HasConstraintName("orderdetails_orderid_fkey");

                    b.HasOne("Lab13_HenryVentura.Domain.Entities.Product", "Product")
                        .WithMany("Orderdetails")
                        .HasForeignKey("Productid")
                        .IsRequired()
                        .HasConstraintName("orderdetails_productid_fkey");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Order", b =>
                {
                    b.Navigation("Orderdetails");
                });

            modelBuilder.Entity("Lab13_HenryVentura.Domain.Entities.Product", b =>
                {
                    b.Navigation("Orderdetails");
                });
#pragma warning restore 612, 618
        }
    }
}
